### ISSUE TITLE
Why does the library print optional parameters?

### ISSUE THREAD

**Issue by schopenhauer** [sebhildebrandt/koa-ip-geo#2]
Why does the library output the white and black list of IP addresses, as per console.log commands below?

```
  console.log(conf.whiteListIP);
  console.log(conf.blackListIP);
```

**Comment by sebhildebrandt** [comment]
Sorry, my fault. Forgot to remove debugging commands... just published a are version 2.0.2 with removed `console.log`

Thank you for having an eye on it ...
